version: '3'
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    restart: always
    environment: 
      - xpack.security.enabled=false
      - discovery.type=single-node

    volumes: 
      - elasticsearch_data:/usr/share/elasticsearch/data

    ports:
     - 9200:9200
     - 9300:9300

volumes: 
  elasticsearch_data:

networks: 
  essite: